#!/bin/sh
set -eu
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:pitti/systemd-semaphore
sudo apt-get update

sudo apt-get install -y pkg-config liblzma-dev libcurl4-gnutls-dev libgcrypt-dev libacl1-dev libfuse-dev rsync python3 meson

meson build
ninja -C build

echo
echo "============= Running tests as user =============="
ninja -C build test

echo
echo "============= Running tests as root =============="
sudo ninja -C build test
